[features]
seeds = false
[programs.localnet]
auction = "4oGFTts1oTHgUQZt1DMcQN7BRiJiR2KunLdTuDNZyv1L"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/stefi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
